"""add schedule unique constraint

Revision ID: d5dc78eb5f80
Revises: 1647a3f1e028
Create Date: 2026-10-04 20:07:27.013984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dc78eb5f80'
down_revision: Union[str, Sequence[str], None] = '1647a3f1e028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_schedule_group_date_lesson', 'schedule', ['group_name', 'date', 'lesson_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_schedule_group_date_lesson', 'schedule', type_='unique')
    # ### end Alembic commands ###
